# vim:ft=kitty

## name:     Ayu
## author:   dempfi (ayu)
## license:  MIT
## upstream: https://ayutheme.com/
## blurb:    Ayu terminal palette using the bright syntax accents from ayutheme.com.

# The basic colors
foreground              #E6E1CF
background              #0F1419
selection_foreground    #E6E1CF
selection_background    #253340

# Cursor colors
cursor                  #FFCD66
cursor_text_color       #0F1419

# URL underline color when hovering with mouse
url_color               #5CCFE6

# Kitty window border colors
active_border_color     #95E6CB
inactive_border_color   #1F2430
bell_border_color       #FFCD66

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0F1419
active_tab_background   #FFCD66
inactive_tab_foreground #B3B1AD
inactive_tab_background #1F2430
tab_bar_background      #0F1419

# Colors for marks (marked text in the terminal)
mark1_foreground #0F1419
mark1_background #73D0FF
mark2_foreground #0F1419
mark2_background #95E6CB
mark3_foreground #0F1419
mark3_background #D5FF80

# The 16 terminal colors

# black
color0  #0B0E14
color8  #4D5566

# red
color1  #F28779
color9  #F28779

# green
color2  #D5FF80
color10 #D5FF80

# yellow
color3  #FFCD66
color11 #FFCD66

# blue
color4  #73D0FF
color12 #73D0FF

# magenta
color5  #DFBFFF
color13 #DFBFFF

# cyan
color6  #5CCFE6
color14 #95E6CB

# white
color7  #E6E1CF
color15 #F9F3E3
